import requests
import re
from bs4 import BeautifulSoup
from openpyxl import Workbook
from tqdm import tqdm  # tqdmをインポート


# URLのリストを指定
urls = [
    'https://job-draft.jp/companies/4',
    'https://job-draft.jp/companies/6',
    'https://job-draft.jp/companies/10',
    'https://job-draft.jp/companies/12',
    'https://job-draft.jp/companies/14',
    'https://job-draft.jp/companies/16',
    'https://job-draft.jp/companies/18',
    'https://job-draft.jp/companies/20',
    'https://job-draft.jp/companies/22',
    'https://job-draft.jp/companies/24',
    'https://job-draft.jp/companies/26',
    'https://job-draft.jp/companies/30',
    'https://job-draft.jp/companies/32',
    'https://job-draft.jp/companies/34',
    'https://job-draft.jp/companies/36',
    'https://job-draft.jp/companies/38',
    'https://job-draft.jp/companies/40',
    'https://job-draft.jp/companies/42',
    'https://job-draft.jp/companies/44',
    'https://job-draft.jp/companies/46',
    'https://job-draft.jp/companies/48',
    'https://job-draft.jp/companies/52',
    'https://job-draft.jp/companies/54',
    'https://job-draft.jp/companies/56',
    'https://job-draft.jp/companies/58',
    'https://job-draft.jp/companies/60',
    'https://job-draft.jp/companies/62',
    'https://job-draft.jp/companies/64',
    'https://job-draft.jp/companies/66',
    'https://job-draft.jp/companies/70',
    'https://job-draft.jp/companies/72',
    'https://job-draft.jp/companies/74',
    'https://job-draft.jp/companies/78',
    'https://job-draft.jp/companies/80',
    'https://job-draft.jp/companies/82',
    'https://job-draft.jp/companies/84',
    'https://job-draft.jp/companies/86',
    'https://job-draft.jp/companies/88',
    'https://job-draft.jp/companies/90',
    'https://job-draft.jp/companies/96',
    'https://job-draft.jp/companies/98',
    'https://job-draft.jp/companies/100',
    'https://job-draft.jp/companies/104',
    'https://job-draft.jp/companies/106',
    'https://job-draft.jp/companies/112',
    'https://job-draft.jp/companies/116',
    'https://job-draft.jp/companies/120',
    'https://job-draft.jp/companies/122',
    'https://job-draft.jp/companies/124',
    'https://job-draft.jp/companies/126',
    'https://job-draft.jp/companies/130',
    'https://job-draft.jp/companies/132',
    'https://job-draft.jp/companies/134',
    'https://job-draft.jp/companies/138',
    'https://job-draft.jp/companies/140',
    'https://job-draft.jp/companies/142',
    'https://job-draft.jp/companies/144',
    'https://job-draft.jp/companies/148',
    'https://job-draft.jp/companies/150',
    'https://job-draft.jp/companies/152',
    'https://job-draft.jp/companies/154',
    'https://job-draft.jp/companies/156',
    'https://job-draft.jp/companies/158',
    'https://job-draft.jp/companies/160',
    'https://job-draft.jp/companies/162',
    'https://job-draft.jp/companies/164',
    'https://job-draft.jp/companies/166',
    'https://job-draft.jp/companies/168',
    'https://job-draft.jp/companies/170',
    'https://job-draft.jp/companies/172',
    'https://job-draft.jp/companies/174',
    'https://job-draft.jp/companies/176',
    'https://job-draft.jp/companies/178',
    'https://job-draft.jp/companies/180',
    'https://job-draft.jp/companies/182',
    'https://job-draft.jp/companies/184',
    'https://job-draft.jp/companies/186',
    'https://job-draft.jp/companies/188',
    'https://job-draft.jp/companies/190',
    'https://job-draft.jp/companies/192',
    'https://job-draft.jp/companies/194',
    'https://job-draft.jp/companies/196',
    'https://job-draft.jp/companies/198',
    'https://job-draft.jp/companies/200',
    'https://job-draft.jp/companies/202',
    'https://job-draft.jp/companies/204',
    'https://job-draft.jp/companies/206',
    'https://job-draft.jp/companies/208',
    'https://job-draft.jp/companies/210',
    'https://job-draft.jp/companies/212',
    'https://job-draft.jp/companies/214',
    'https://job-draft.jp/companies/216',
    'https://job-draft.jp/companies/218',
    'https://job-draft.jp/companies/220',
    'https://job-draft.jp/companies/224',
    'https://job-draft.jp/companies/226',
    'https://job-draft.jp/companies/232',
    'https://job-draft.jp/companies/236',
    'https://job-draft.jp/companies/240',
    'https://job-draft.jp/companies/242',
    'https://job-draft.jp/companies/244',
    'https://job-draft.jp/companies/248',
    'https://job-draft.jp/companies/250',
    'https://job-draft.jp/companies/254',
    'https://job-draft.jp/companies/256',
    'https://job-draft.jp/companies/264',
    'https://job-draft.jp/companies/266',
    'https://job-draft.jp/companies/268',
    'https://job-draft.jp/companies/270',
    'https://job-draft.jp/companies/272',
    'https://job-draft.jp/companies/274',
    'https://job-draft.jp/companies/276',
    'https://job-draft.jp/companies/280',
    'https://job-draft.jp/companies/286',
    'https://job-draft.jp/companies/288',
    'https://job-draft.jp/companies/294',
    'https://job-draft.jp/companies/296',
    'https://job-draft.jp/companies/302',
    'https://job-draft.jp/companies/304',
    'https://job-draft.jp/companies/306',
    'https://job-draft.jp/companies/310',
    'https://job-draft.jp/companies/312',
    'https://job-draft.jp/companies/314',
    'https://job-draft.jp/companies/316',
    'https://job-draft.jp/companies/318',
    'https://job-draft.jp/companies/320',
    'https://job-draft.jp/companies/322',
    'https://job-draft.jp/companies/324',
    'https://job-draft.jp/companies/326',
    'https://job-draft.jp/companies/328',
    'https://job-draft.jp/companies/330',
    'https://job-draft.jp/companies/332',
    'https://job-draft.jp/companies/335',
    'https://job-draft.jp/companies/338',
    'https://job-draft.jp/companies/341',
    'https://job-draft.jp/companies/344',
    'https://job-draft.jp/companies/347',
    'https://job-draft.jp/companies/353',
    'https://job-draft.jp/companies/356',
    'https://job-draft.jp/companies/359',
    'https://job-draft.jp/companies/365',
    'https://job-draft.jp/companies/368',
    'https://job-draft.jp/companies/371',
    'https://job-draft.jp/companies/374',
    'https://job-draft.jp/companies/377',
    'https://job-draft.jp/companies/383',
    'https://job-draft.jp/companies/386',
    'https://job-draft.jp/companies/389',
    'https://job-draft.jp/companies/395',
    'https://job-draft.jp/companies/398',
    'https://job-draft.jp/companies/401',
    'https://job-draft.jp/companies/404',
    'https://job-draft.jp/companies/407',
    'https://job-draft.jp/companies/410',
    'https://job-draft.jp/companies/416',
    'https://job-draft.jp/companies/419',
    'https://job-draft.jp/companies/422',
    'https://job-draft.jp/companies/425',
    'https://job-draft.jp/companies/428',
    'https://job-draft.jp/companies/437',
    'https://job-draft.jp/companies/440',
    'https://job-draft.jp/companies/443',
    'https://job-draft.jp/companies/446',
    'https://job-draft.jp/companies/449',
    'https://job-draft.jp/companies/452',
    'https://job-draft.jp/companies/455',
    'https://job-draft.jp/companies/458',
    'https://job-draft.jp/companies/461',
    'https://job-draft.jp/companies/464',
    'https://job-draft.jp/companies/467',
    'https://job-draft.jp/companies/473',
    'https://job-draft.jp/companies/482',
    'https://job-draft.jp/companies/485',
    'https://job-draft.jp/companies/491',
    'https://job-draft.jp/companies/494',
    'https://job-draft.jp/companies/497',
    'https://job-draft.jp/companies/500',
    'https://job-draft.jp/companies/506',
    'https://job-draft.jp/companies/509',
    'https://job-draft.jp/companies/515',
    'https://job-draft.jp/companies/518',
    'https://job-draft.jp/companies/521',
    'https://job-draft.jp/companies/524',
    'https://job-draft.jp/companies/527',
    'https://job-draft.jp/companies/530',
    'https://job-draft.jp/companies/536',
    'https://job-draft.jp/companies/539',
    'https://job-draft.jp/companies/542',
    'https://job-draft.jp/companies/545',
    'https://job-draft.jp/companies/548',
    'https://job-draft.jp/companies/557',
    'https://job-draft.jp/companies/560',
    'https://job-draft.jp/companies/563',
    'https://job-draft.jp/companies/566',
    'https://job-draft.jp/companies/572',
    'https://job-draft.jp/companies/578',
    'https://job-draft.jp/companies/584',
    'https://job-draft.jp/companies/587',
    'https://job-draft.jp/companies/593',
    'https://job-draft.jp/companies/596',
    'https://job-draft.jp/companies/599',
    'https://job-draft.jp/companies/608',
    'https://job-draft.jp/companies/617',
    'https://job-draft.jp/companies/623',
    'https://job-draft.jp/companies/626',
    'https://job-draft.jp/companies/632',
    'https://job-draft.jp/companies/635',
    'https://job-draft.jp/companies/638',
    'https://job-draft.jp/companies/641',
    'https://job-draft.jp/companies/644',
    'https://job-draft.jp/companies/647',
    'https://job-draft.jp/companies/650',
    'https://job-draft.jp/companies/653',
    'https://job-draft.jp/companies/659',
    'https://job-draft.jp/companies/662',
    'https://job-draft.jp/companies/668',
    'https://job-draft.jp/companies/671',
    'https://job-draft.jp/companies/680',
    'https://job-draft.jp/companies/686',
    'https://job-draft.jp/companies/689',
    'https://job-draft.jp/companies/692',
    'https://job-draft.jp/companies/695',
    'https://job-draft.jp/companies/698',
    'https://job-draft.jp/companies/701',
    'https://job-draft.jp/companies/704',
    'https://job-draft.jp/companies/710',
    'https://job-draft.jp/companies/713',
    'https://job-draft.jp/companies/716',
    'https://job-draft.jp/companies/719',
    'https://job-draft.jp/companies/722',
    'https://job-draft.jp/companies/725',
    'https://job-draft.jp/companies/728',
    'https://job-draft.jp/companies/731',
    'https://job-draft.jp/companies/734',
    'https://job-draft.jp/companies/737',
    'https://job-draft.jp/companies/743',
    'https://job-draft.jp/companies/746',
    'https://job-draft.jp/companies/749',
    'https://job-draft.jp/companies/752',
    'https://job-draft.jp/companies/755',
    'https://job-draft.jp/companies/758',
    'https://job-draft.jp/companies/764',
    'https://job-draft.jp/companies/767',
    'https://job-draft.jp/companies/782',
    'https://job-draft.jp/companies/785',
    'https://job-draft.jp/companies/788',
    'https://job-draft.jp/companies/821',
    'https://job-draft.jp/companies/824',
    'https://job-draft.jp/companies/827',
    'https://job-draft.jp/companies/830',
    'https://job-draft.jp/companies/833',
    'https://job-draft.jp/companies/836',
    'https://job-draft.jp/companies/842',
    'https://job-draft.jp/companies/845',
    'https://job-draft.jp/companies/848',
    'https://job-draft.jp/companies/851',
    'https://job-draft.jp/companies/854',
    'https://job-draft.jp/companies/857',
    'https://job-draft.jp/companies/860',
    'https://job-draft.jp/companies/863',
    'https://job-draft.jp/companies/866',
    'https://job-draft.jp/companies/869',
    'https://job-draft.jp/companies/872',
    'https://job-draft.jp/companies/875',
    'https://job-draft.jp/companies/878',
    'https://job-draft.jp/companies/884',
    'https://job-draft.jp/companies/887',
    'https://job-draft.jp/companies/890',
    'https://job-draft.jp/companies/893',
    'https://job-draft.jp/companies/899',
    'https://job-draft.jp/companies/905',
    'https://job-draft.jp/companies/911',
    'https://job-draft.jp/companies/914',
    'https://job-draft.jp/companies/917',
    'https://job-draft.jp/companies/920',
    'https://job-draft.jp/companies/926',
    'https://job-draft.jp/companies/929',
    'https://job-draft.jp/companies/932',
    'https://job-draft.jp/companies/935',
    'https://job-draft.jp/companies/938',
    'https://job-draft.jp/companies/941',
    'https://job-draft.jp/companies/944',
    'https://job-draft.jp/companies/947',
    'https://job-draft.jp/companies/950',
    'https://job-draft.jp/companies/953',
    'https://job-draft.jp/companies/962',
    'https://job-draft.jp/companies/965',
    'https://job-draft.jp/companies/968',
    'https://job-draft.jp/companies/971',
    'https://job-draft.jp/companies/974',
    'https://job-draft.jp/companies/977',
    'https://job-draft.jp/companies/983',
    'https://job-draft.jp/companies/986',
    'https://job-draft.jp/companies/989',
    'https://job-draft.jp/companies/992',
    'https://job-draft.jp/companies/998',
    'https://job-draft.jp/companies/1001',
    'https://job-draft.jp/companies/1004',
    'https://job-draft.jp/companies/1007',
    'https://job-draft.jp/companies/1013',
    'https://job-draft.jp/companies/1019',
    'https://job-draft.jp/companies/1022',
    'https://job-draft.jp/companies/1025',
    'https://job-draft.jp/companies/1028',
    'https://job-draft.jp/companies/1031',
    'https://job-draft.jp/companies/1034',
    'https://job-draft.jp/companies/1040',
    'https://job-draft.jp/companies/1043',
    'https://job-draft.jp/companies/1052',
    'https://job-draft.jp/companies/1055',
    'https://job-draft.jp/companies/1058',
    'https://job-draft.jp/companies/1064',
    'https://job-draft.jp/companies/1067',
    'https://job-draft.jp/companies/1073',
    'https://job-draft.jp/companies/1076',
    'https://job-draft.jp/companies/1079',
    'https://job-draft.jp/companies/1082',
    'https://job-draft.jp/companies/1085',
    'https://job-draft.jp/companies/1088',
    'https://job-draft.jp/companies/1094',
    'https://job-draft.jp/companies/1106',
    'https://job-draft.jp/companies/1109',
    'https://job-draft.jp/companies/1112',
    'https://job-draft.jp/companies/1118',
    'https://job-draft.jp/companies/1121',
    'https://job-draft.jp/companies/1124',
    'https://job-draft.jp/companies/1130',
    'https://job-draft.jp/companies/1133',
    'https://job-draft.jp/companies/1136',
    'https://job-draft.jp/companies/1139',
    'https://job-draft.jp/companies/1148',
    'https://job-draft.jp/companies/1154',
    'https://job-draft.jp/companies/1160',
    'https://job-draft.jp/companies/1166',
    'https://job-draft.jp/companies/1169',
    'https://job-draft.jp/companies/1172',
    'https://job-draft.jp/companies/1175',
    'https://job-draft.jp/companies/1181',
    'https://job-draft.jp/companies/1184',
    'https://job-draft.jp/companies/1190',
    'https://job-draft.jp/companies/1193',
    'https://job-draft.jp/companies/1196',
    'https://job-draft.jp/companies/1199',
    'https://job-draft.jp/companies/1205',
    'https://job-draft.jp/companies/1208',
    'https://job-draft.jp/companies/1211',
    'https://job-draft.jp/companies/1214',
    'https://job-draft.jp/companies/1217',
    'https://job-draft.jp/companies/1220',
    'https://job-draft.jp/companies/1226',
    'https://job-draft.jp/companies/1229',
    'https://job-draft.jp/companies/1232',
    'https://job-draft.jp/companies/1235',
    'https://job-draft.jp/companies/1238',
    'https://job-draft.jp/companies/1241',
    'https://job-draft.jp/companies/1244',
    'https://job-draft.jp/companies/1250',
    'https://job-draft.jp/companies/1253',
    'https://job-draft.jp/companies/1256',
    'https://job-draft.jp/companies/1259',
    'https://job-draft.jp/companies/1262',
    'https://job-draft.jp/companies/1265',
    'https://job-draft.jp/companies/1268',
    'https://job-draft.jp/companies/1271',
    'https://job-draft.jp/companies/1274',
    'https://job-draft.jp/companies/1277',
    'https://job-draft.jp/companies/1280',
    'https://job-draft.jp/companies/1283',
    'https://job-draft.jp/companies/1286',
    'https://job-draft.jp/companies/1289',
    'https://job-draft.jp/companies/1292',
    'https://job-draft.jp/companies/1295',
    'https://job-draft.jp/companies/1301',
    'https://job-draft.jp/companies/1304',
    'https://job-draft.jp/companies/1307',
    'https://job-draft.jp/companies/1310',
    'https://job-draft.jp/companies/1313',
    'https://job-draft.jp/companies/1316',
    'https://job-draft.jp/companies/1319',
    'https://job-draft.jp/companies/1322',
    'https://job-draft.jp/companies/1325',
    'https://job-draft.jp/companies/1328',
    'https://job-draft.jp/companies/1331',
    'https://job-draft.jp/companies/1334',
    'https://job-draft.jp/companies/1337',
    'https://job-draft.jp/companies/1343',
    'https://job-draft.jp/companies/1346',
    'https://job-draft.jp/companies/1349',
    'https://job-draft.jp/companies/1352',
    'https://job-draft.jp/companies/1355',
    'https://job-draft.jp/companies/1358',
    'https://job-draft.jp/companies/1361',
    'https://job-draft.jp/companies/1364',
    'https://job-draft.jp/companies/1367',
    'https://job-draft.jp/companies/1370',
    'https://job-draft.jp/companies/1373',
    'https://job-draft.jp/companies/1376',
    'https://job-draft.jp/companies/1379',
    'https://job-draft.jp/companies/1382',
    'https://job-draft.jp/companies/1385',
    'https://job-draft.jp/companies/1388',
    'https://job-draft.jp/companies/1391',
    'https://job-draft.jp/companies/1394',
    'https://job-draft.jp/companies/1397',
    'https://job-draft.jp/companies/1400',
    'https://job-draft.jp/companies/1403',
    'https://job-draft.jp/companies/1406',
    'https://job-draft.jp/companies/1409',
    'https://job-draft.jp/companies/1412',
    'https://job-draft.jp/companies/1415',
    'https://job-draft.jp/companies/1418',
    'https://job-draft.jp/companies/1421',
    'https://job-draft.jp/companies/1424',
    'https://job-draft.jp/companies/1427',
    'https://job-draft.jp/companies/1430',
    'https://job-draft.jp/companies/1433',
    'https://job-draft.jp/companies/1436',
    'https://job-draft.jp/companies/1439',
    'https://job-draft.jp/companies/1442',
    'https://job-draft.jp/companies/1445',
    'https://job-draft.jp/companies/1448',
    'https://job-draft.jp/companies/1451',
    'https://job-draft.jp/companies/1454',
    'https://job-draft.jp/companies/1457',
    'https://job-draft.jp/companies/1460',
    'https://job-draft.jp/companies/1463',
    'https://job-draft.jp/companies/1466',
    'https://job-draft.jp/companies/1469',
    'https://job-draft.jp/companies/1472',
    'https://job-draft.jp/companies/1475',
    'https://job-draft.jp/companies/1478',
    'https://job-draft.jp/companies/1481',
    'https://job-draft.jp/companies/1484',
    'https://job-draft.jp/companies/1487',
    'https://job-draft.jp/companies/1493',
    'https://job-draft.jp/companies/1496',
    'https://job-draft.jp/companies/1499',
    'https://job-draft.jp/companies/1502',
    'https://job-draft.jp/companies/1505',
    'https://job-draft.jp/companies/1508',
    'https://job-draft.jp/companies/1511',
    'https://job-draft.jp/companies/1514',
    'https://job-draft.jp/companies/1517',
    'https://job-draft.jp/companies/1520',
    'https://job-draft.jp/companies/1523',
    'https://job-draft.jp/companies/1526',
    'https://job-draft.jp/companies/1529',
    'https://job-draft.jp/companies/1532',
    'https://job-draft.jp/companies/1535',
    'https://job-draft.jp/companies/1538',
    'https://job-draft.jp/companies/1541',
    'https://job-draft.jp/companies/1544',
    'https://job-draft.jp/companies/1547',
    'https://job-draft.jp/companies/1550',
    'https://job-draft.jp/companies/1553',
    'https://job-draft.jp/companies/1556',
    'https://job-draft.jp/companies/1559',
    'https://job-draft.jp/companies/1562',
    'https://job-draft.jp/companies/1565',
    'https://job-draft.jp/companies/1571',
    'https://job-draft.jp/companies/1574',
    'https://job-draft.jp/companies/1577',
    'https://job-draft.jp/companies/1580',
    'https://job-draft.jp/companies/1583',
    'https://job-draft.jp/companies/1586',
    'https://job-draft.jp/companies/1589',
    'https://job-draft.jp/companies/1592',
    'https://job-draft.jp/companies/1595',
    'https://job-draft.jp/companies/1598',
    'https://job-draft.jp/companies/1601',
    'https://job-draft.jp/companies/1604',
    'https://job-draft.jp/companies/1607',
    'https://job-draft.jp/companies/1610',
    'https://job-draft.jp/companies/1613',
    'https://job-draft.jp/companies/1616',
    'https://job-draft.jp/companies/1622',
    'https://job-draft.jp/companies/1625',
    'https://job-draft.jp/companies/1628',
    'https://job-draft.jp/companies/1631',
    'https://job-draft.jp/companies/1634',
    'https://job-draft.jp/companies/1637',
    'https://job-draft.jp/companies/1640',
    'https://job-draft.jp/companies/1643',
    'https://job-draft.jp/companies/1646',
    'https://job-draft.jp/companies/1649',
    'https://job-draft.jp/companies/1650',
    'https://job-draft.jp/companies/1651',
    'https://job-draft.jp/companies/1652',
    'https://job-draft.jp/companies/1653',
    'https://job-draft.jp/companies/1654',
    'https://job-draft.jp/companies/1655',
    'https://job-draft.jp/companies/1656',
    'https://job-draft.jp/companies/1657',
    'https://job-draft.jp/companies/1658',
    'https://job-draft.jp/companies/1659',
    'https://job-draft.jp/companies/1660',
    'https://job-draft.jp/companies/1661',
    'https://job-draft.jp/companies/1662',
    'https://job-draft.jp/companies/1663',
    'https://job-draft.jp/companies/1664',
    'https://job-draft.jp/companies/1665',
    'https://job-draft.jp/companies/1666',
    'https://job-draft.jp/companies/1667',
    'https://job-draft.jp/companies/1668',
    'https://job-draft.jp/companies/1669',
    'https://job-draft.jp/companies/1670',
    'https://job-draft.jp/companies/1671',
    'https://job-draft.jp/companies/1672',
    'https://job-draft.jp/companies/1673',
    'https://job-draft.jp/companies/1674',
    'https://job-draft.jp/companies/1675',
    'https://job-draft.jp/companies/1676',
    'https://job-draft.jp/companies/1677',
    'https://job-draft.jp/companies/1678',
    'https://job-draft.jp/companies/1679',
    'https://job-draft.jp/companies/1680',
    'https://job-draft.jp/companies/1681',
    'https://job-draft.jp/companies/1683',
    'https://job-draft.jp/companies/1684',
    'https://job-draft.jp/companies/1685',
    'https://job-draft.jp/companies/1686',
    'https://job-draft.jp/companies/1687',
    'https://job-draft.jp/companies/1688',
    'https://job-draft.jp/companies/1689',
    'https://job-draft.jp/companies/1690',
    'https://job-draft.jp/companies/1691',
    'https://job-draft.jp/companies/1692',
    'https://job-draft.jp/companies/1693',
    'https://job-draft.jp/companies/1694',
    'https://job-draft.jp/companies/1696',
    'https://job-draft.jp/companies/1697',
    'https://job-draft.jp/companies/1698',
    'https://job-draft.jp/companies/1699',
    'https://job-draft.jp/companies/1700',
    'https://job-draft.jp/companies/1701',
    'https://job-draft.jp/companies/1702',
    'https://job-draft.jp/companies/1703',
    'https://job-draft.jp/companies/1704',
    'https://job-draft.jp/companies/1705',
    'https://job-draft.jp/companies/1706',
    'https://job-draft.jp/companies/1707',
    'https://job-draft.jp/companies/1708',
    'https://job-draft.jp/companies/1709',
    'https://job-draft.jp/companies/1710',
    'https://job-draft.jp/companies/1711',
    'https://job-draft.jp/companies/1712',
    'https://job-draft.jp/companies/1713',
    'https://job-draft.jp/companies/1715',
    'https://job-draft.jp/companies/1716',
    'https://job-draft.jp/companies/1717',
    'https://job-draft.jp/companies/1718',
    'https://job-draft.jp/companies/1719',
    'https://job-draft.jp/companies/1720',
    'https://job-draft.jp/companies/1721',
    'https://job-draft.jp/companies/1722',
    'https://job-draft.jp/companies/1723',
    'https://job-draft.jp/companies/1724',
    'https://job-draft.jp/companies/1725',
    'https://job-draft.jp/companies/1726',
    'https://job-draft.jp/companies/1727',
    'https://job-draft.jp/companies/1728',
    'https://job-draft.jp/companies/1729',
    'https://job-draft.jp/companies/1730',
    'https://job-draft.jp/companies/1731',
    'https://job-draft.jp/companies/1732',
    'https://job-draft.jp/companies/1733',
    'https://job-draft.jp/companies/1734',
    'https://job-draft.jp/companies/1735',
    'https://job-draft.jp/companies/1736',
    'https://job-draft.jp/companies/1737',
    'https://job-draft.jp/companies/1738',
    'https://job-draft.jp/companies/1739',
    'https://job-draft.jp/companies/1740',
    'https://job-draft.jp/companies/1741',
    'https://job-draft.jp/companies/1742',
    'https://job-draft.jp/companies/1743',
    'https://job-draft.jp/companies/1744',
    'https://job-draft.jp/companies/1745',
    'https://job-draft.jp/companies/1746',
    'https://job-draft.jp/companies/1747',
    'https://job-draft.jp/companies/1748',
    'https://job-draft.jp/companies/1749',
    'https://job-draft.jp/companies/1750',
    'https://job-draft.jp/companies/1751',
    'https://job-draft.jp/companies/1752',
    'https://job-draft.jp/companies/1753',
    'https://job-draft.jp/companies/1754',
    'https://job-draft.jp/companies/1755',
    'https://job-draft.jp/companies/1756',
    'https://job-draft.jp/companies/1757',
    'https://job-draft.jp/companies/1758',
    'https://job-draft.jp/companies/1759',
    'https://job-draft.jp/companies/1760',
    'https://job-draft.jp/companies/1761',
    'https://job-draft.jp/companies/1762',
    'https://job-draft.jp/companies/1763',
    'https://job-draft.jp/companies/1764',
    'https://job-draft.jp/companies/1765',
    'https://job-draft.jp/companies/1767',
    'https://job-draft.jp/companies/1768',
    'https://job-draft.jp/companies/1769',
    'https://job-draft.jp/companies/1770',
    'https://job-draft.jp/companies/1771',
    'https://job-draft.jp/companies/1772',
    'https://job-draft.jp/companies/1773',
    'https://job-draft.jp/companies/1774',
    'https://job-draft.jp/companies/1775',
    'https://job-draft.jp/companies/1776',
    'https://job-draft.jp/companies/1777',
    'https://job-draft.jp/companies/1778',
    'https://job-draft.jp/companies/1779',
    'https://job-draft.jp/companies/1780',
    'https://job-draft.jp/companies/1781',
    'https://job-draft.jp/companies/1782',
    'https://job-draft.jp/companies/1783',
    'https://job-draft.jp/companies/1787',
    'https://job-draft.jp/companies/1788',
    'https://job-draft.jp/companies/1790',
    'https://job-draft.jp/companies/1791',
    'https://job-draft.jp/companies/1792',
    'https://job-draft.jp/companies/1793',
    'https://job-draft.jp/companies/1794',
    'https://job-draft.jp/companies/1795',
    'https://job-draft.jp/companies/1796',
    'https://job-draft.jp/companies/1797',
    'https://job-draft.jp/companies/1798',
    'https://job-draft.jp/companies/1799',
    'https://job-draft.jp/companies/1800',
    'https://job-draft.jp/companies/1801',
    'https://job-draft.jp/companies/1802',
    'https://job-draft.jp/companies/1803',
    'https://job-draft.jp/companies/1804',
    'https://job-draft.jp/companies/1805',
    'https://job-draft.jp/companies/1806',
    'https://job-draft.jp/companies/1807',
    # 他のURLもここに追加
]

# エクセルファイルを作成
workbook = Workbook()
sheet = workbook.active

# 列の見出しを追加
sheet['A1'] = '会社名'
sheet['B1'] = '指名数'
sheet['C1'] = '最高提示年収'
sheet['D1'] = '最低提示年収'
sheet['E1'] = '平均提示年収'
sheet['F1'] = '設立年'
sheet['G1'] = '上場'
sheet['H1'] = '資本金'
sheet['I1'] = '売上高'
sheet['J1'] = '従業員数'
sheet['K1'] = '平均年齢'
sheet['L1'] = '住所'
sheet['M1'] = '会社HP'
# 他の列の見出しをここに追加

# URLのリストを処理
for i, url in enumerate(tqdm(urls), start=2):  # tqdmを使って進捗バーを表示
    # ウェブサイトからデータを取得
    response = requests.get(url)
    web_content = response.text

    # ウェブサイトから取得したデータを解析
    local_soup = BeautifulSoup(web_content, 'html.parser')

    # ターゲットの要素を取得
    company_name = local_soup.find('h1', class_='p-profile-canopy__name').text if local_soup.find('h1', class_='p-profile-canopy__name') else 'データなし'
    nomination_count = local_soup.find('dt', text='指名数').find_next('span', class_='emphasis-40').text if local_soup.find('dt', text='指名数') else 'データなし'
    max_salary = local_soup.find('dt', text='最高提示年収').find_next('span', class_='emphasis-40').text if local_soup.find('dt', text='最高提示年収') else 'データなし'
    min_salary = local_soup.find('dt', text='最低提示年収').find_next('span', class_='emphasis-40').text if local_soup.find('dt', text='最低提示年収') else 'データなし'
    avg_salary = local_soup.find('dt', text='平均提示年収').find_next('span', class_='emphasis-40').text if local_soup.find('dt', text='平均提示年収') else 'データなし'
    establishment_year = local_soup.find('th', text='設立年').find_next('td').text if local_soup.find('th', text='設立年') else 'データなし'
    listing = local_soup.find('th', text='上場').find_next('td').text if local_soup.find('th', text='上場') else 'データなし'
    capital = local_soup.find('th', text='資本金').find_next('td').text if local_soup.find('th', text='資本金') else 'データなし'
    sales = local_soup.find('th', text='売上高').find_next('td').text if local_soup.find('th', text='売上高') else 'データなし'
    employees = local_soup.find('th', text='従業員数').find_next('td').text if local_soup.find('th', text='従業員数') else 'データなし'
    avg_age = local_soup.find('th', text='平均年齢').find_next('td').text if local_soup.find('th', text='平均年齢') else 'データなし'
    address = local_soup.find('th', text='住所').find_next('td').text if local_soup.find('th', text='住所') else 'データなし'
    company_hp = local_soup.find('th', text='会社HP').find_next('td').find('a')['href'] if local_soup.find('th', text='会社HP') else 'データなし'
    # 他の要素をここに追加

    # ターゲットの要素が存在するか確認
    if company_name and nomination_count:
        # セルにデータを書き込む
        sheet[f'A{i}'] = company_name
        sheet[f'B{i}'] = nomination_count
        sheet[f'C{i}'] = max_salary
        sheet[f'D{i}'] = min_salary
        sheet[f'E{i}'] = avg_salary
        sheet[f'F{i}'] = establishment_year
        sheet[f'G{i}'] = listing
        sheet[f'H{i}'] = capital
        sheet[f'I{i}'] = sales
        sheet[f'J{i}'] = employees
        sheet[f'K{i}'] = avg_age
        sheet[f'L{i}'] = address
        sheet[f'M{i}'] = company_hp
        # 他のセルにもデータを追加

# エクセルファイルを保存
workbook.save('output.xlsx')

print('データをエクセルに書き込みました。')